name: Tests
on:
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v1
    - uses: rwjblue/setup-volta@v1

    - name: Install
      run: yarn install
    - name: Linting
      run: yarn lint:js
    - name: Type Safety
      run: yarn lint:types

  test:
    name: Testing
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v1
    - uses: rwjblue/setup-volta@v1

    - name: Install
      run: yarn install
    - name: Test
      run: yarn test
